# Gold To SQL Ingestion Using SQL Alchemy

- Load up imports

In [1]:
from sqlalchemy import create_engine, text, Integer, Float, Date, String, BigInteger
import urllib

import pandas as pd

### Load Up Dataframes for each table

In [2]:
dimCargoMeasurementCSV = pd.read_csv('GoldLayerData/dim_cargo_measurement.csv')
dimConsigneeCSV = pd.read_csv('GoldLayerData/dim_consignee.csv')
dimPortCSV = pd.read_csv('GoldLayerData/dim_port.csv')
dimShipperCSV = pd.read_csv('GoldLayerData/dim_shipper.csv')
dimVesselCSV = pd.read_csv('GoldLayerData/dim_vessel.csv')
factHeaderCSV = pd.read_csv('GoldLayerData/fact_header.csv')

In [3]:
dimCargoMeasurementCSV

             identifier manifest_unit measurement_unit
0             201901012           PKG     Cubic Meters
1             201901013           PKG     Cubic Meters
2             201901014           CTN     Cubic Meters
3             201901015           PCL     Cubic Meters
4             201901016           CTN     Cubic Meters
...                 ...           ...              ...
34038974  2020092382684           CTN              NaN
34038975  2020092382685           CTN              NaN
34038976  2020092382686           CTN              NaN
34038977  2020092382687           PKG     Cubic Meters
34038978  2020092382688           PCS              NaN

[34038979 rows x 3 columns]

In [4]:
dimConsigneeCSV.dtypes

consignee_id           int64
consignee_name           str
consignee_address_1      str
consignee_address_2      str
consignee_address_3      str
dtype: object

In [5]:
dimPortCSV.dtypes

port_id      int64
port_name      str
dtype: object

In [6]:
dimShipperCSV.dtypes

shipper_id                 int64
shipper_party_name           str
shipper_party_address_1      str
shipper_party_address_2      str
shipper_party_address_3      str
dtype: object

In [7]:
dimVesselCSV

       vessel_id vessel_country_code       vessel_name
0              1                  AD       ACACIA MING
1              2                  AD         AGAMEMNON
2              3                  AD          AIN SNAN
3              4                  AD          AL QIBLA
4              5                  AD           ALLEGRO
...          ...                 ...               ...
38093      38094                 NaN         ONE CRANE
38094      38095                 NaN        ONE CYGNUS
38095      38096                 NaN          SCHUBERT
38096      38097                 NaN  YM ENLIGHTENMENT
38097      38098                 NaN        YM EXPRESS

[38098 rows x 3 columns]

In [8]:
factHeaderCSV

,identifier,estimated_arrival_date,actual_arrival_date,port_of_unlading_id,foreign_port_of_lading_qualifier_id,foreign_port_of_lading_id,port_of_destination_id,foreign_port_of_destination_qualifier_id,foreign_port_of_destination_id,vessel_id,shipper_id,consignee_id,manifest_quantity,weight,measurement
0,201901012,2018-03-28,2018-03-30,887,1269,1176,NaN,NaN,NaN,27388,NaN,NaN,3350,44599,12756
1,201901013,2018-03-28,2018-03-30,887,1269,207,NaN,NaN,NaN,27388,NaN,NaN,642,9258,2539
2,201901014,2018-03-28,2018-03-30,887,1269,207,NaN,NaN,NaN,27388,NaN,NaN,2743,34760,136
3,201901015,2018-03-28,2018-03-30,887,1269,207,NaN,NaN,NaN,27388,1296312.0,1559462.0,37,19537,0
4,201901016,2018-03-28,2018-03-30,887,1269,207,NaN,NaN,NaN,27388,NaN,NaN,3469,42107,6003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34038974,2020092382684,2020-09-08,2020-09-11,1273,1269,1629,NaN,NaN,NaN,37472,675504.0,1997811.0,386,7370,0
34038975,2020092382685,2020-07-19,2020-07-20,712,1269,1288,NaN,NaN,NaN,27003,3294336.0,409782.0,338,9633,0
34038976,2020092382686,2020-07-19,2020-07-20,712,1269,1288,NaN,NaN,NaN,27003,3294336.0,409782.0,432,7906,0
34038977,2020092382687,2020-07-20,2020-07-20,716,1269,1623,NaN,NaN,NaN,32116,NaN,NaN,40,19750,99
34038978,2020092382688,2020-09-29,2020-09-22,716,1269,747,NaN,NaN,NaN,29259,497061.0,2507356.0,960,19980,0

### Windows Authentication to SQL Database

- Build the SQLAlchemy Connection String

In [9]:
# Build the SQLAlchemy Connection String
params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=CargoImporters;"
    "Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}", fast_executemany=True)

- Test the Connection

In [10]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

---

In [11]:
from math import ceil

def load_with_progress(
    df,
    table_name,
    engine,
    schema="dbo",
    chunksize=25_000,
    dtype=None
):
    total_rows = len(df)
    total_chunks = ceil(total_rows / chunksize)

    for i, start in enumerate(range(0, total_rows, chunksize), start=1):
        end = min(start + chunksize, total_rows)
        chunk = df.iloc[start:end]

        chunk.to_sql(
            table_name,
            engine,
            schema=schema,
            if_exists="replace" if i == 1 else "append",
            index=False,
            method=None,
            dtype=dtype
        )

        print(
            f"✅ Loaded rows {start:,}–{end:,} "
            f"({end:,}/{total_rows:,}) | "
            f"Chunk {i}/{total_chunks}"
        )

### Load Up Data to SQL Database

- dim_cargo_measurement table

In [12]:
load_with_progress(
    df=dimCargoMeasurementCSV,
    table_name="dim_cargo_measurement",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "identifier": BigInteger(),
        "manifest_unit": String(10),
        "measurement_unit": String(50)
    }
)

✅ Loaded rows 0–25,000 (25,000/34,038,979) | Chunk 1/1362
✅ Loaded rows 25,000–50,000 (50,000/34,038,979) | Chunk 2/1362
✅ Loaded rows 50,000–75,000 (75,000/34,038,979) | Chunk 3/1362
✅ Loaded rows 75,000–100,000 (100,000/34,038,979) | Chunk 4/1362
✅ Loaded rows 100,000–125,000 (125,000/34,038,979) | Chunk 5/1362
✅ Loaded rows 125,000–150,000 (150,000/34,038,979) | Chunk 6/1362
✅ Loaded rows 150,000–175,000 (175,000/34,038,979) | Chunk 7/1362
✅ Loaded rows 175,000–200,000 (200,000/34,038,979) | Chunk 8/1362
✅ Loaded rows 200,000–225,000 (225,000/34,038,979) | Chunk 9/1362
✅ Loaded rows 225,000–250,000 (250,000/34,038,979) | Chunk 10/1362
✅ Loaded rows 250,000–275,000 (275,000/34,038,979) | Chunk 11/1362
✅ Loaded rows 275,000–300,000 (300,000/34,038,979) | Chunk 12/1362
✅ Loaded rows 300,000–325,000 (325,000/34,038,979) | Chunk 13/1362
✅ Loaded rows 325,000–350,000 (350,000/34,038,979) | Chunk 14/1362
✅ Loaded rows 350,000–375,000 (375,000/34,038,979) | Chunk 15/1362
✅ Loaded rows 375,000–400,000 (400,000/34,038,979) | Chunk 16/1362
✅ Loaded rows 400,000–425,000 (425,000/34,038,979) | Chunk 17/1362
✅ Loaded rows 425,000–450,000 (450,000/34,038,979) | Chunk 18/1362
✅ Loaded rows 450,000–475,000 (475,000/34,038,979) | Chunk 19/1362
✅ Loaded rows 475,000–500,000 (500,000/34,038,979) | Chunk 20/1362
✅ Loaded rows 500,000–525,000 (525,000/34,038,979) | Chunk 21/1362
✅ Loaded rows 525,000–550,000 (550,000/34,038,979) | Chunk 22/1362
✅ Loaded rows 550,000–575,000 (575,000/34,038,979) | Chunk 23/1362
✅ Loaded rows 575,000–600,000 (600,000/34,038,979) | Chunk 24/1362
✅ Loaded rows 600,000–625,000 (625,000/34,038,979) | Chunk 25/1362
✅ Loaded rows 625,000–650,000 (650,000/34,038,979) | Chunk 26/1362
✅ Loaded rows 650,000–675,000 (675,000/34,038,979) | Chunk 27/1362
✅ Loaded rows 675,000–700,000 (700,000/34,038,979) | Chunk 28/1362
✅ Loaded rows 700,000–725,000 (725,000/34,038,979) | Chunk 29/1362
✅ Loaded rows 725,000–750,000 (750,000/34,038,979) | Chunk 30/1362
✅ Loaded rows 750,000–775,000 (775,000/34,038,979) | Chunk 31/1362
✅ Loaded rows 775,000–800,000 (800,000/34,038,979) | Chunk 32/1362
✅ Loaded rows 800,000–825,000 (825,000/34,038,979) | Chunk 33/1362
✅ Loaded rows 825,000–850,000 (850,000/34,038,979) | Chunk 34/1362
✅ Loaded rows 850,000–875,000 (875,000/34,038,979) | Chunk 35/1362
✅ Loaded rows 875,000–900,000 (900,000/34,038,979) | Chunk 36/1362
✅ Loaded rows 900,000–925,000 (925,000/34,038,979) | Chunk 37/1362
✅ Loaded rows 925,000–950,000 (950,000/34,038,979) | Chunk 38/1362
✅ Loaded rows 950,000–975,000 (975,000/34,038,979) | Chunk 39/1362
✅ Loaded rows 975,000–1,000,000 (1,000,000/34,038,979) | Chunk 40/1362
✅ Loaded rows 1,000,000–1,025,000 (1,025,000/34,038,979) | Chunk 41/1362
✅ Loaded rows 1,025,000–1,050,000 (1,050,000/34,038,979) | Chunk 42/1362
✅ Loaded rows 1,050,000–1,075,000 (1,075,000/34,038,979) | Chunk 43/1362
✅ Loaded rows 1,075,000–1,100,000 (1,100,000/34,038,979) | Chunk 44/1362
✅ Loaded rows 1,100,000–1,125,000 (1,125,000/34,038,979) | Chunk 45/1362
✅ Loaded rows 1,125,000–1,150,000 (1,150,000/34,038,979) | Chunk 46/1362
✅ Loaded rows 1,150,000–1,175,000 (1,175,000/34,038,979) | Chunk 47/1362
✅ Loaded rows 1,175,000–1,200,000 (1,200,000/34,038,979) | Chunk 48/1362
✅ Loaded rows 1,200,000–1,225,000 (1,225,000/34,038,979) | Chunk 49/1362
✅ Loaded rows 1,225,000–1,250,000 (1,250,000/34,038,979) | Chunk 50/1362
✅ Loaded rows 1,250,000–1,275,000 (1,275,000/34,038,979) | Chunk 51/1362
✅ Loaded rows 1,275,000–1,300,000 (1,300,000/34,038,979) | Chunk 52/1362
✅ Loaded rows 1,300,000–1,325,000 (1,325,000/34,038,979) | Chunk 53/1362
✅ Loaded rows 1,325,000–1,350,000 (1,350,000/34,038,979) | Chunk 54/1362
✅ Loaded rows 1,350,000–1,375,000 (1,375,000/34,038,979) | Chunk 55/1362
✅ Loaded rows 1,375,000–1,400,000 (1,400,000/34,038,979) | Chunk 56/1362
✅ Loaded rows 1,400,000–1,425,000 (1,425,000/34,038,979) | Chunk 57/1362
✅ Loaded rows 1,425,000–1,450,000 (1,450,000/34,038,979) | Chunk 58/1362
✅ Loaded rows 1,450,000–1,475,000 (1,475,000/34,038,979) | Chunk 59/1362
✅ Loaded rows 1,475,000–1,500,000 (1,500,000/34,038,979) | Chunk 60/1362
✅ Loaded rows 1,500,000–1,525,000 (1,525,000/34,038,979) | Chunk 61/1362
✅ Loaded rows 1,525,000–1,550,000 (1,550,000/34,038,979) | Chunk 62/1362
✅ Loaded rows 1,550,000–1,575,000 (1,575,000/34,038,979) | Chunk 63/1362
✅ Loaded rows 1,575,000–1,600,000 (1,600,000/34,038,979) | Chunk 64/1362
✅ Loaded rows 1,600,000–1,625,000 (1,625,000/34,038,979) | Chunk 65/1362
✅ Loaded rows 1,625,000–1,650,000 (1,650,000/34,038,979) | Chunk 66/1362
✅ Loaded rows 1,650,000–1,675,000 (1,675,000/34,038,979) | Chunk 67/1362
✅ Loaded rows 1,675,000–1,700,000 (1,700,000/34,038,979) | Chunk 68/1362
✅ Loaded rows 1,700,000–1,725,000 (1,725,000/34,038,979) | Chunk 69/1362
✅ Loaded rows 1,725,000–1,750,000 (1,750,000/34,038,979) | Chunk 70/1362
✅ Loaded rows 1,750,000–1,775,000 (1,775,000/34,038,979) | Chunk 71/1362
✅ Loaded rows 1,775,000–1,800,000 (1,800,000/34,038,979) | Chunk 72/1362
✅ Loaded rows 1,800,000–1,825,000 (1,825,000/34,038,979) | Chunk 73/1362
✅ Loaded rows 1,825,000–1,850,000 (1,850,000/34,038,979) | Chunk 74/1362
✅ Loaded rows 1,850,000–1,875,000 (1,875,000/34,038,979) | Chunk 75/1362
✅ Loaded rows 1,875,000–1,900,000 (1,900,000/34,038,979) | Chunk 76/1362
✅ Loaded rows 1,900,000–1,925,000 (1,925,000/34,038,979) | Chunk 77/1362
✅ Loaded rows 1,925,000–1,950,000 (1,950,000/34,038,979) | Chunk 78/1362
✅ Loaded rows 1,950,000–1,975,000 (1,975,000/34,038,979) | Chunk 79/1362
✅ Loaded rows 1,975,000–2,000,000 (2,000,000/34,038,979) | Chunk 80/1362
✅ Loaded rows 2,000,000–2,025,000 (2,025,000/34,038,979) | Chunk 81/1362
✅ Loaded rows 2,025,000–2,050,000 (2,050,000/34,038,979) | Chunk 82/1362
✅ Loaded rows 2,050,000–2,075,000 (2,075,000/34,038,979) | Chunk 83/1362
✅ Loaded rows 2,075,000–2,100,000 (2,100,000/34,038,979) | Chunk 84/1362
✅ Loaded rows 2,100,000–2,125,000 (2,125,000/34,038,979) | Chunk 85/1362
✅ Loaded rows 2,125,000–2,150,000 (2,150,000/34,038,979) | Chunk 86/1362
✅ Loaded rows 2,150,000–2,175,000 (2,175,000/34,038,979) | Chunk 87/1362
✅ Loaded rows 2,175,000–2,200,000 (2,200,000/34,038,979) | Chunk 88/1362
✅ Loaded rows 2,200,000–2,225,000 (2,225,000/34,038,979) | Chunk 89/1362
✅ Loaded rows 2,225,000–2,250,000 (2,250,000/34,038,979) | Chunk 90/1362
✅ Loaded rows 2,250,000–2,275,000 (2,275,000/34,038,979) | Chunk 91/1362
✅ Loaded rows 2,275,000–2,300,000 (2,300,000/34,038,979) | Chunk 92/1362
✅ Loaded rows 2,300,000–2,325,000 (2,325,000/34,038,979) | Chunk 93/1362
✅ Loaded rows 2,325,000–2,350,000 (2,350,000/34,038,979) | Chunk 94/1362
✅ Loaded rows 2,350,000–2,375,000 (2,375,000/34,038,979) | Chunk 95/1362
✅ Loaded rows 2,375,000–2,400,000 (2,400,000/34,038,979) | Chunk 96/1362
✅ Loaded rows 2,400,000–2,425,000 (2,425,000/34,038,979) | Chunk 97/1362
✅ Loaded rows 2,425,000–2,450,000 (2,450,000/34,038,979) | Chunk 98/1362
✅ Loaded rows 2,450,000–2,475,000 (2,475,000/34,038,979) | Chunk 99/1362
✅ Loaded rows 2,475,000–2,500,000 (2,500,000/34,038,979) | Chunk 100/1362
✅ Loaded rows 2,500,000–2,525,000 (2,525,000/34,038,979) | Chunk 101/1362
✅ Loaded rows 2,525,000–2,550,000 (2,550,000/34,038,979) | Chunk 102/1362
✅ Loaded rows 2,550,000–2,575,000 (2,575,000/34,038,979) | Chunk 103/1362
✅ Loaded rows 2,575,000–2,600,000 (2,600,000/34,038,979) | Chunk 104/1362
✅ Loaded rows 2,600,000–2,625,000 (2,625,000/34,038,979) | Chunk 105/1362
✅ Loaded rows 2,625,000–2,650,000 (2,650,000/34,038,979) | Chunk 106/1362
✅ Loaded rows 2,650,000–2,675,000 (2,675,000/34,038,979) | Chunk 107/1362
✅ Loaded rows 2,675,000–2,700,000 (2,700,000/34,038,979) | Chunk 108/1362
✅ Loaded rows 2,700,000–2,725,000 (2,725,000/34,038,979) | Chunk 109/1362
✅ Loaded rows 2,725,000–2,750,000 (2,750,000/34,038,979) | Chunk 110/1362
✅ Loaded rows 2,750,000–2,775,000 (2,775,000/34,038,979) | Chunk 111/1362
✅ Loaded rows 2,775,000–2,800,000 (2,800,000/34,038,979) | Chunk 112/1362
✅ Loaded rows 2,800,000–2,825,000 (2,825,000/34,038,979) | Chunk 113/1362
✅ Loaded rows 2,825,000–2,850,000 (2,850,000/34,038,979) | Chunk 114/1362
✅ Loaded rows 2,850,000–2,875,000 (2,875,000/34,038,979) | Chunk 115/1362
✅ Loaded rows 2,875,000–2,900,000 (2,900,000/34,038,979) | Chunk 116/1362
✅ Loaded rows 2,900,000–2,925,000 (2,925,000/34,038,979) | Chunk 117/1362
✅ Loaded rows 2,925,000–2,950,000 (2,950,000/34,038,979) | Chunk 118/1362
✅ Loaded rows 2,950,000–2,975,000 (2,975,000/34,038,979) | Chunk 119/1362
✅ Loaded rows 2,975,000–3,000,000 (3,000,000/34,038,979) | Chunk 120/1362
✅ Loaded rows 3,000,000–3,025,000 (3,025,000/34,038,979) | Chunk 121/1362
✅ Loaded rows 3,025,000–3,050,000 (3,050,000/34,038,979) | Chunk 122/1362
✅ Loaded rows 3,050,000–3,075,000 (3,075,000/34,038,979) | Chunk 123/1362
✅ Loaded rows 3,075,000–3,100,000 (3,100,000/34,038,979) | Chunk 124/1362
✅ Loaded rows 3,100,000–3,125,000 (3,125,000/34,038,979) | Chunk 125/1362
✅ Loaded rows 3,125,000–3,150,000 (3,150,000/34,038,979) | Chunk 126/1362
✅ Loaded rows 3,150,000–3,175,000 (3,175,000/34,038,979) | Chunk 127/1362
✅ Loaded rows 3,175,000–3,200,000 (3,200,000/34,038,979) | Chunk 128/1362
✅ Loaded rows 3,200,000–3,225,000 (3,225,000/34,038,979) | Chunk 129/1362
✅ Loaded rows 3,225,000–3,250,000 (3,250,000/34,038,979) | Chunk 130/1362
✅ Loaded rows 3,250,000–3,275,000 (3,275,000/34,038,979) | Chunk 131/1362
✅ Loaded rows 3,275,000–3,300,000 (3,300,000/34,038,979) | Chunk 132/1362
✅ Loaded rows 3,300,000–3,325,000 (3,325,000/34,038,979) | Chunk 133/1362
✅ Loaded rows 3,325,000–3,350,000 (3,350,000/34,038,979) | Chunk 134/1362
✅ Loaded rows 3,350,000–3,375,000 (3,375,000/34,038,979) | Chunk 135/1362
✅ Loaded rows 3,375,000–3,400,000 (3,400,000/34,038,979) | Chunk 136/1362
✅ Loaded rows 3,400,000–3,425,000 (3,425,000/34,038,979) | Chunk 137/1362
✅ Loaded rows 3,425,000–3,450,000 (3,450,000/34,038,979) | Chunk 138/1362
✅ Loaded rows 3,450,000–3,475,000 (3,475,000/34,038,979) | Chunk 139/1362
✅ Loaded rows 3,475,000–3,500,000 (3,500,000/34,038,979) | Chunk 140/1362
✅ Loaded rows 3,500,000–3,525,000 (3,525,000/34,038,979) | Chunk 141/1362
✅ Loaded rows 3,525,000–3,550,000 (3,550,000/34,038,979) | Chunk 142/1362
✅ Loaded rows 3,550,000–3,575,000 (3,575,000/34,038,979) | Chunk 143/1362
✅ Loaded rows 3,575,000–3,600,000 (3,600,000/34,038,979) | Chunk 144/1362
✅ Loaded rows 3,600,000–3,625,000 (3,625,000/34,038,979) | Chunk 145/1362
✅ Loaded rows 3,625,000–3,650,000 (3,650,000/34,038,979) | Chunk 146/1362
✅ Loaded rows 3,650,000–3,675,000 (3,675,000/34,038,979) | Chunk 147/1362
✅ Loaded rows 3,675,000–3,700,000 (3,700,000/34,038,979) | Chunk 148/1362
✅ Loaded rows 3,700,000–3,725,000 (3,725,000/34,038,979) | Chunk 149/1362
✅ Loaded rows 3,725,000–3,750,000 (3,750,000/34,038,979) | Chunk 150/1362
✅ Loaded rows 3,750,000–3,775,000 (3,775,000/34,038,979) | Chunk 151/1362
✅ Loaded rows 3,775,000–3,800,000 (3,800,000/34,038,979) | Chunk 152/1362
✅ Loaded rows 3,800,000–3,825,000 (3,825,000/34,038,979) | Chunk 153/1362
✅ Loaded rows 3,825,000–3,850,000 (3,850,000/34,038,979) | Chunk 154/1362
✅ Loaded rows 3,850,000–3,875,000 (3,875,000/34,038,979) | Chunk 155/1362
✅ Loaded rows 3,875,000–3,900,000 (3,900,000/34,038,979) | Chunk 156/1362
✅ Loaded rows 3,900,000–3,925,000 (3,925,000/34,038,979) | Chunk 157/1362
✅ Loaded rows 3,925,000–3,950,000 (3,950,000/34,038,979) | Chunk 158/1362
✅ Loaded rows 3,950,000–3,975,000 (3,975,000/34,038,979) | Chunk 159/1362
✅ Loaded rows 3,975,000–4,000,000 (4,000,000/34,038,979) | Chunk 160/1362
✅ Loaded rows 4,000,000–4,025,000 (4,025,000/34,038,979) | Chunk 161/1362
✅ Loaded rows 4,025,000–4,050,000 (4,050,000/34,038,979) | Chunk 162/1362
✅ Loaded rows 4,050,000–4,075,000 (4,075,000/34,038,979) | Chunk 163/1362
✅ Loaded rows 4,075,000–4,100,000 (4,100,000/34,038,979) | Chunk 164/1362
✅ Loaded rows 4,100,000–4,125,000 (4,125,000/34,038,979) | Chunk 165/1362
✅ Loaded rows 4,125,000–4,150,000 (4,150,000/34,038,979) | Chunk 166/1362
✅ Loaded rows 4,150,000–4,175,000 (4,175,000/34,038,979) | Chunk 167/1362
✅ Loaded rows 4,175,000–4,200,000 (4,200,000/34,038,979) | Chunk 168/1362
✅ Loaded rows 4,200,000–4,225,000 (4,225,000/34,038,979) | Chunk 169/1362
✅ Loaded rows 4,225,000–4,250,000 (4,250,000/34,038,979) | Chunk 170/1362
✅ Loaded rows 4,250,000–4,275,000 (4,275,000/34,038,979) | Chunk 171/1362
✅ Loaded rows 4,275,000–4,300,000 (4,300,000/34,038,979) | Chunk 172/1362
✅ Loaded rows 4,300,000–4,325,000 (4,325,000/34,038,979) | Chunk 173/1362
✅ Loaded rows 4,325,000–4,350,000 (4,350,000/34,038,979) | Chunk 174/1362
✅ Loaded rows 4,350,000–4,375,000 (4,375,000/34,038,979) | Chunk 175/1362
✅ Loaded rows 4,375,000–4,400,000 (4,400,000/34,038,979) | Chunk 176/1362
✅ Loaded rows 4,400,000–4,425,000 (4,425,000/34,038,979) | Chunk 177/1362
✅ Loaded rows 4,425,000–4,450,000 (4,450,000/34,038,979) | Chunk 178/1362
✅ Loaded rows 4,450,000–4,475,000 (4,475,000/34,038,979) | Chunk 179/1362
✅ Loaded rows 4,475,000–4,500,000 (4,500,000/34,038,979) | Chunk 180/1362
✅ Loaded rows 4,500,000–4,525,000 (4,525,000/34,038,979) | Chunk 181/1362
✅ Loaded rows 4,525,000–4,550,000 (4,550,000/34,038,979) | Chunk 182/1362
✅ Loaded rows 4,550,000–4,575,000 (4,575,000/34,038,979) | Chunk 183/1362
✅ Loaded rows 4,575,000–4,600,000 (4,600,000/34,038,979) | Chunk 184/1362
✅ Loaded rows 4,600,000–4,625,000 (4,625,000/34,038,979) | Chunk 185/1362
✅ Loaded rows 4,625,000–4,650,000 (4,650,000/34,038,979) | Chunk 186/1362
✅ Loaded rows 4,650,000–4,675,000 (4,675,000/34,038,979) | Chunk 187/1362
✅ Loaded rows 4,675,000–4,700,000 (4,700,000/34,038,979) | Chunk 188/1362
✅ Loaded rows 4,700,000–4,725,000 (4,725,000/34,038,979) | Chunk 189/1362
✅ Loaded rows 4,725,000–4,750,000 (4,750,000/34,038,979) | Chunk 190/1362
✅ Loaded rows 4,750,000–4,775,000 (4,775,000/34,038,979) | Chunk 191/1362
✅ Loaded rows 4,775,000–4,800,000 (4,800,000/34,038,979) | Chunk 192/1362
✅ Loaded rows 4,800,000–4,825,000 (4,825,000/34,038,979) | Chunk 193/1362
✅ Loaded rows 4,825,000–4,850,000 (4,850,000/34,038,979) | Chunk 194/1362
✅ Loaded rows 4,850,000–4,875,000 (4,875,000/34,038,979) | Chunk 195/1362
✅ Loaded rows 4,875,000–4,900,000 (4,900,000/34,038,979) | Chunk 196/1362
✅ Loaded rows 4,900,000–4,925,000 (4,925,000/34,038,979) | Chunk 197/1362
✅ Loaded rows 4,925,000–4,950,000 (4,950,000/34,038,979) | Chunk 198/1362
✅ Loaded rows 4,950,000–4,975,000 (4,975,000/34,038,979) | Chunk 199/1362
✅ Loaded rows 4,975,000–5,000,000 (5,000,000/34,038,979) | Chunk 200/1362
✅ Loaded rows 5,000,000–5,025,000 (5,025,000/34,038,979) | Chunk 201/1362
✅ Loaded rows 5,025,000–5,050,000 (5,050,000/34,038,979) | Chunk 202/1362
✅ Loaded rows 5,050,000–5,075,000 (5,075,000/34,038,979) | Chunk 203/1362
✅ Loaded rows 5,075,000–5,100,000 (5,100,000/34,038,979) | Chunk 204/1362
✅ Loaded rows 5,100,000–5,125,000 (5,125,000/34,038,979) | Chunk 205/1362
✅ Loaded rows 5,125,000–5,150,000 (5,150,000/34,038,979) | Chunk 206/1362
✅ Loaded rows 5,150,000–5,175,000 (5,175,000/34,038,979) | Chunk 207/1362
✅ Loaded rows 5,175,000–5,200,000 (5,200,000/34,038,979) | Chunk 208/1362
✅ Loaded rows 5,200,000–5,225,000 (5,225,000/34,038,979) | Chunk 209/1362
✅ Loaded rows 5,225,000–5,250,000 (5,250,000/34,038,979) | Chunk 210/1362
✅ Loaded rows 5,250,000–5,275,000 (5,275,000/34,038,979) | Chunk 211/1362
✅ Loaded rows 5,275,000–5,300,000 (5,300,000/34,038,979) | Chunk 212/1362
✅ Loaded rows 5,300,000–5,325,000 (5,325,000/34,038,979) | Chunk 213/1362
✅ Loaded rows 5,325,000–5,350,000 (5,350,000/34,038,979) | Chunk 214/1362
✅ Loaded rows 5,350,000–5,375,000 (5,375,000/34,038,979) | Chunk 215/1362
✅ Loaded rows 5,375,000–5,400,000 (5,400,000/34,038,979) | Chunk 216/1362
✅ Loaded rows 5,400,000–5,425,000 (5,425,000/34,038,979) | Chunk 217/1362
✅ Loaded rows 5,425,000–5,450,000 (5,450,000/34,038,979) | Chunk 218/1362
✅ Loaded rows 5,450,000–5,475,000 (5,475,000/34,038,979) | Chunk 219/1362
✅ Loaded rows 5,475,000–5,500,000 (5,500,000/34,038,979) | Chunk 220/1362
✅ Loaded rows 5,500,000–5,525,000 (5,525,000/34,038,979) | Chunk 221/1362
✅ Loaded rows 5,525,000–5,550,000 (5,550,000/34,038,979) | Chunk 222/1362
✅ Loaded rows 5,550,000–5,575,000 (5,575,000/34,038,979) | Chunk 223/1362
✅ Loaded rows 5,575,000–5,600,000 (5,600,000/34,038,979) | Chunk 224/1362
✅ Loaded rows 5,600,000–5,625,000 (5,625,000/34,038,979) | Chunk 225/1362
✅ Loaded rows 5,625,000–5,650,000 (5,650,000/34,038,979) | Chunk 226/1362
✅ Loaded rows 5,650,000–5,675,000 (5,675,000/34,038,979) | Chunk 227/1362
✅ Loaded rows 5,675,000–5,700,000 (5,700,000/34,038,979) | Chunk 228/1362
✅ Loaded rows 5,700,000–5,725,000 (5,725,000/34,038,979) | Chunk 229/1362
✅ Loaded rows 5,725,000–5,750,000 (5,750,000/34,038,979) | Chunk 230/1362
✅ Loaded rows 5,750,000–5,775,000 (5,775,000/34,038,979) | Chunk 231/1362
✅ Loaded rows 5,775,000–5,800,000 (5,800,000/34,038,979) | Chunk 232/1362
✅ Loaded rows 5,800,000–5,825,000 (5,825,000/34,038,979) | Chunk 233/1362
✅ Loaded rows 5,825,000–5,850,000 (5,850,000/34,038,979) | Chunk 234/1362
✅ Loaded rows 5,850,000–5,875,000 (5,875,000/34,038,979) | Chunk 235/1362
✅ Loaded rows 5,875,000–5,900,000 (5,900,000/34,038,979) | Chunk 236/1362
✅ Loaded rows 5,900,000–5,925,000 (5,925,000/34,038,979) | Chunk 237/1362
✅ Loaded rows 5,925,000–5,950,000 (5,950,000/34,038,979) | Chunk 238/1362
✅ Loaded rows 5,950,000–5,975,000 (5,975,000/34,038,979) | Chunk 239/1362
✅ Loaded rows 5,975,000–6,000,000 (6,000,000/34,038,979) | Chunk 240/1362
✅ Loaded rows 6,000,000–6,025,000 (6,025,000/34,038,979) | Chunk 241/1362
✅ Loaded rows 6,025,000–6,050,000 (6,050,000/34,038,979) | Chunk 242/1362
✅ Loaded rows 6,050,000–6,075,000 (6,075,000/34,038,979) | Chunk 243/1362
✅ Loaded rows 6,075,000–6,100,000 (6,100,000/34,038,979) | Chunk 244/1362
✅ Loaded rows 6,100,000–6,125,000 (6,125,000/34,038,979) | Chunk 245/1362
✅ Loaded rows 6,125,000–6,150,000 (6,150,000/34,038,979) | Chunk 246/1362
✅ Loaded rows 6,150,000–6,175,000 (6,175,000/34,038,979) | Chunk 247/1362
✅ Loaded rows 6,175,000–6,200,000 (6,200,000/34,038,979) | Chunk 248/1362
✅ Loaded rows 6,200,000–6,225,000 (6,225,000/34,038,979) | Chunk 249/1362
✅ Loaded rows 6,225,000–6,250,000 (6,250,000/34,038,979) | Chunk 250/1362
✅ Loaded rows 6,250,000–6,275,000 (6,275,000/34,038,979) | Chunk 251/1362
✅ Loaded rows 6,275,000–6,300,000 (6,300,000/34,038,979) | Chunk 252/1362
✅ Loaded rows 6,300,000–6,325,000 (6,325,000/34,038,979) | Chunk 253/1362
✅ Loaded rows 6,325,000–6,350,000 (6,350,000/34,038,979) | Chunk 254/1362
✅ Loaded rows 6,350,000–6,375,000 (6,375,000/34,038,979) | Chunk 255/1362
✅ Loaded rows 6,375,000–6,400,000 (6,400,000/34,038,979) | Chunk 256/1362
✅ Loaded rows 6,400,000–6,425,000 (6,425,000/34,038,979) | Chunk 257/1362
✅ Loaded rows 6,425,000–6,450,000 (6,450,000/34,038,979) | Chunk 258/1362
✅ Loaded rows 6,450,000–6,475,000 (6,475,000/34,038,979) | Chunk 259/1362
✅ Loaded rows 6,475,000–6,500,000 (6,500,000/34,038,979) | Chunk 260/1362
✅ Loaded rows 6,500,000–6,525,000 (6,525,000/34,038,979) | Chunk 261/1362
✅ Loaded rows 6,525,000–6,550,000 (6,550,000/34,038,979) | Chunk 262/1362
✅ Loaded rows 6,550,000–6,575,000 (6,575,000/34,038,979) | Chunk 263/1362
✅ Loaded rows 6,575,000–6,600,000 (6,600,000/34,038,979) | Chunk 264/1362
✅ Loaded rows 6,600,000–6,625,000 (6,625,000/34,038,979) | Chunk 265/1362
✅ Loaded rows 6,625,000–6,650,000 (6,650,000/34,038,979) | Chunk 266/1362
✅ Loaded rows 6,650,000–6,675,000 (6,675,000/34,038,979) | Chunk 267/1362
✅ Loaded rows 6,675,000–6,700,000 (6,700,000/34,038,979) | Chunk 268/1362
✅ Loaded rows 6,700,000–6,725,000 (6,725,000/34,038,979) | Chunk 269/1362
✅ Loaded rows 6,725,000–6,750,000 (6,750,000/34,038,979) | Chunk 270/1362
✅ Loaded rows 6,750,000–6,775,000 (6,775,000/34,038,979) | Chunk 271/1362
✅ Loaded rows 6,775,000–6,800,000 (6,800,000/34,038,979) | Chunk 272/1362
✅ Loaded rows 6,800,000–6,825,000 (6,825,000/34,038,979) | Chunk 273/1362
✅ Loaded rows 6,825,000–6,850,000 (6,850,000/34,038,979) | Chunk 274/1362
✅ Loaded rows 6,850,000–6,875,000 (6,875,000/34,038,979) | Chunk 275/1362

- dim_consignee table

In [13]:
load_with_progress(
    df=dimConsigneeCSV,
    table_name="dim_consignee",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "consignee_id": BigInteger(),
        "consignee_name": String(255),
        "consignee_address_1": String(255),
        "consignee_address_2": String(255),
        "Consignee_address_3": String(255)
    }
)

✅ Loaded rows 0–25,000 (25,000/3,767,444) | Chunk 1/151
✅ Loaded rows 25,000–50,000 (50,000/3,767,444) | Chunk 2/151
✅ Loaded rows 50,000–75,000 (75,000/3,767,444) | Chunk 3/151
✅ Loaded rows 75,000–100,000 (100,000/3,767,444) | Chunk 4/151
✅ Loaded rows 100,000–125,000 (125,000/3,767,444) | Chunk 5/151
✅ Loaded rows 125,000–150,000 (150,000/3,767,444) | Chunk 6/151
✅ Loaded rows 150,000–175,000 (175,000/3,767,444) | Chunk 7/151
✅ Loaded rows 175,000–200,000 (200,000/3,767,444) | Chunk 8/151
✅ Loaded rows 200,000–225,000 (225,000/3,767,444) | Chunk 9/151
✅ Loaded rows 225,000–250,000 (250,000/3,767,444) | Chunk 10/151
✅ Loaded rows 250,000–275,000 (275,000/3,767,444) | Chunk 11/151
✅ Loaded rows 275,000–300,000 (300,000/3,767,444) | Chunk 12/151
✅ Loaded rows 300,000–325,000 (325,000/3,767,444) | Chunk 13/151
✅ Loaded rows 325,000–350,000 (350,000/3,767,444) | Chunk 14/151
✅ Loaded rows 350,000–375,000 (375,000/3,767,444) | Chunk 15/151
✅ Loaded rows 375,000–400,000 (400,000/3,767,444) | Chunk 16/151
✅ Loaded rows 400,000–425,000 (425,000/3,767,444) | Chunk 17/151
✅ Loaded rows 425,000–450,000 (450,000/3,767,444) | Chunk 18/151
✅ Loaded rows 450,000–475,000 (475,000/3,767,444) | Chunk 19/151
✅ Loaded rows 475,000–500,000 (500,000/3,767,444) | Chunk 20/151
✅ Loaded rows 500,000–525,000 (525,000/3,767,444) | Chunk 21/151
✅ Loaded rows 525,000–550,000 (550,000/3,767,444) | Chunk 22/151
✅ Loaded rows 550,000–575,000 (575,000/3,767,444) | Chunk 23/151
✅ Loaded rows 575,000–600,000 (600,000/3,767,444) | Chunk 24/151
✅ Loaded rows 600,000–625,000 (625,000/3,767,444) | Chunk 25/151
✅ Loaded rows 625,000–650,000 (650,000/3,767,444) | Chunk 26/151
✅ Loaded rows 650,000–675,000 (675,000/3,767,444) | Chunk 27/151
✅ Loaded rows 675,000–700,000 (700,000/3,767,444) | Chunk 28/151
✅ Loaded rows 700,000–725,000 (725,000/3,767,444) | Chunk 29/151
✅ Loaded rows 725,000–750,000 (750,000/3,767,444) | Chunk 30/151
✅ Loaded rows 750,000–775,000 (775,000/3,767,444) | Chunk 31/151
✅ Loaded rows 775,000–800,000 (800,000/3,767,444) | Chunk 32/151
✅ Loaded rows 800,000–825,000 (825,000/3,767,444) | Chunk 33/151
✅ Loaded rows 825,000–850,000 (850,000/3,767,444) | Chunk 34/151
✅ Loaded rows 850,000–875,000 (875,000/3,767,444) | Chunk 35/151
✅ Loaded rows 875,000–900,000 (900,000/3,767,444) | Chunk 36/151
✅ Loaded rows 900,000–925,000 (925,000/3,767,444) | Chunk 37/151
✅ Loaded rows 925,000–950,000 (950,000/3,767,444) | Chunk 38/151
✅ Loaded rows 950,000–975,000 (975,000/3,767,444) | Chunk 39/151
✅ Loaded rows 975,000–1,000,000 (1,000,000/3,767,444) | Chunk 40/151
✅ Loaded rows 1,000,000–1,025,000 (1,025,000/3,767,444) | Chunk 41/151
✅ Loaded rows 1,025,000–1,050,000 (1,050,000/3,767,444) | Chunk 42/151
✅ Loaded rows 1,050,000–1,075,000 (1,075,000/3,767,444) | Chunk 43/151
✅ Loaded rows 1,075,000–1,100,000 (1,100,000/3,767,444) | Chunk 44/151
✅ Loaded rows 1,100,000–1,125,000 (1,125,000/3,767,444) | Chunk 45/151
✅ Loaded rows 1,125,000–1,150,000 (1,150,000/3,767,444) | Chunk 46/151
✅ Loaded rows 1,150,000–1,175,000 (1,175,000/3,767,444) | Chunk 47/151
✅ Loaded rows 1,175,000–1,200,000 (1,200,000/3,767,444) | Chunk 48/151
✅ Loaded rows 1,200,000–1,225,000 (1,225,000/3,767,444) | Chunk 49/151
✅ Loaded rows 1,225,000–1,250,000 (1,250,000/3,767,444) | Chunk 50/151
✅ Loaded rows 1,250,000–1,275,000 (1,275,000/3,767,444) | Chunk 51/151
✅ Loaded rows 1,275,000–1,300,000 (1,300,000/3,767,444) | Chunk 52/151
✅ Loaded rows 1,300,000–1,325,000 (1,325,000/3,767,444) | Chunk 53/151
✅ Loaded rows 1,325,000–1,350,000 (1,350,000/3,767,444) | Chunk 54/151
✅ Loaded rows 1,350,000–1,375,000 (1,375,000/3,767,444) | Chunk 55/151
✅ Loaded rows 1,375,000–1,400,000 (1,400,000/3,767,444) | Chunk 56/151
✅ Loaded rows 1,400,000–1,425,000 (1,425,000/3,767,444) | Chunk 57/151
✅ Loaded rows 1,425,000–1,450,000 (1,450,000/3,767,444) | Chunk 58/151
✅ Loaded rows 1,450,000–1,475,000 (1,475,000/3,767,444) | Chunk 59/151
✅ Loaded rows 1,475,000–1,500,000 (1,500,000/3,767,444) | Chunk 60/151
✅ Loaded rows 1,500,000–1,525,000 (1,525,000/3,767,444) | Chunk 61/151
✅ Loaded rows 1,525,000–1,550,000 (1,550,000/3,767,444) | Chunk 62/151
✅ Loaded rows 1,550,000–1,575,000 (1,575,000/3,767,444) | Chunk 63/151
✅ Loaded rows 1,575,000–1,600,000 (1,600,000/3,767,444) | Chunk 64/151
✅ Loaded rows 1,600,000–1,625,000 (1,625,000/3,767,444) | Chunk 65/151
✅ Loaded rows 1,625,000–1,650,000 (1,650,000/3,767,444) | Chunk 66/151
✅ Loaded rows 1,650,000–1,675,000 (1,675,000/3,767,444) | Chunk 67/151
✅ Loaded rows 1,675,000–1,700,000 (1,700,000/3,767,444) | Chunk 68/151
✅ Loaded rows 1,700,000–1,725,000 (1,725,000/3,767,444) | Chunk 69/151
✅ Loaded rows 1,725,000–1,750,000 (1,750,000/3,767,444) | Chunk 70/151
✅ Loaded rows 1,750,000–1,775,000 (1,775,000/3,767,444) | Chunk 71/151
✅ Loaded rows 1,775,000–1,800,000 (1,800,000/3,767,444) | Chunk 72/151
✅ Loaded rows 1,800,000–1,825,000 (1,825,000/3,767,444) | Chunk 73/151
✅ Loaded rows 1,825,000–1,850,000 (1,850,000/3,767,444) | Chunk 74/151
✅ Loaded rows 1,850,000–1,875,000 (1,875,000/3,767,444) | Chunk 75/151
✅ Loaded rows 1,875,000–1,900,000 (1,900,000/3,767,444) | Chunk 76/151
✅ Loaded rows 1,900,000–1,925,000 (1,925,000/3,767,444) | Chunk 77/151
✅ Loaded rows 1,925,000–1,950,000 (1,950,000/3,767,444) | Chunk 78/151
✅ Loaded rows 1,950,000–1,975,000 (1,975,000/3,767,444) | Chunk 79/151
✅ Loaded rows 1,975,000–2,000,000 (2,000,000/3,767,444) | Chunk 80/151
✅ Loaded rows 2,000,000–2,025,000 (2,025,000/3,767,444) | Chunk 81/151
✅ Loaded rows 2,025,000–2,050,000 (2,050,000/3,767,444) | Chunk 82/151
✅ Loaded rows 2,050,000–2,075,000 (2,075,000/3,767,444) | Chunk 83/151
✅ Loaded rows 2,075,000–2,100,000 (2,100,000/3,767,444) | Chunk 84/151
✅ Loaded rows 2,100,000–2,125,000 (2,125,000/3,767,444) | Chunk 85/151
✅ Loaded rows 2,125,000–2,150,000 (2,150,000/3,767,444) | Chunk 86/151
✅ Loaded rows 2,150,000–2,175,000 (2,175,000/3,767,444) | Chunk 87/151
✅ Loaded rows 2,175,000–2,200,000 (2,200,000/3,767,444) | Chunk 88/151
✅ Loaded rows 2,200,000–2,225,000 (2,225,000/3,767,444) | Chunk 89/151
✅ Loaded rows 2,225,000–2,250,000 (2,250,000/3,767,444) | Chunk 90/151
✅ Loaded rows 2,250,000–2,275,000 (2,275,000/3,767,444) | Chunk 91/151
✅ Loaded rows 2,275,000–2,300,000 (2,300,000/3,767,444) | Chunk 92/151
✅ Loaded rows 2,300,000–2,325,000 (2,325,000/3,767,444) | Chunk 93/151
✅ Loaded rows 2,325,000–2,350,000 (2,350,000/3,767,444) | Chunk 94/151
✅ Loaded rows 2,350,000–2,375,000 (2,375,000/3,767,444) | Chunk 95/151
✅ Loaded rows 2,375,000–2,400,000 (2,400,000/3,767,444) | Chunk 96/151
✅ Loaded rows 2,400,000–2,425,000 (2,425,000/3,767,444) | Chunk 97/151
✅ Loaded rows 2,425,000–2,450,000 (2,450,000/3,767,444) | Chunk 98/151
✅ Loaded rows 2,450,000–2,475,000 (2,475,000/3,767,444) | Chunk 99/151
✅ Loaded rows 2,475,000–2,500,000 (2,500,000/3,767,444) | Chunk 100/151
✅ Loaded rows 2,500,000–2,525,000 (2,525,000/3,767,444) | Chunk 101/151
✅ Loaded rows 2,525,000–2,550,000 (2,550,000/3,767,444) | Chunk 102/151
✅ Loaded rows 2,550,000–2,575,000 (2,575,000/3,767,444) | Chunk 103/151
✅ Loaded rows 2,575,000–2,600,000 (2,600,000/3,767,444) | Chunk 104/151
✅ Loaded rows 2,600,000–2,625,000 (2,625,000/3,767,444) | Chunk 105/151
✅ Loaded rows 2,625,000–2,650,000 (2,650,000/3,767,444) | Chunk 106/151
✅ Loaded rows 2,650,000–2,675,000 (2,675,000/3,767,444) | Chunk 107/151
✅ Loaded rows 2,675,000–2,700,000 (2,700,000/3,767,444) | Chunk 108/151
✅ Loaded rows 2,700,000–2,725,000 (2,725,000/3,767,444) | Chunk 109/151
✅ Loaded rows 2,725,000–2,750,000 (2,750,000/3,767,444) | Chunk 110/151
✅ Loaded rows 2,750,000–2,775,000 (2,775,000/3,767,444) | Chunk 111/151
✅ Loaded rows 2,775,000–2,800,000 (2,800,000/3,767,444) | Chunk 112/151
✅ Loaded rows 2,800,000–2,825,000 (2,825,000/3,767,444) | Chunk 113/151
✅ Loaded rows 2,825,000–2,850,000 (2,850,000/3,767,444) | Chunk 114/151
✅ Loaded rows 2,850,000–2,875,000 (2,875,000/3,767,444) | Chunk 115/151
✅ Loaded rows 2,875,000–2,900,000 (2,900,000/3,767,444) | Chunk 116/151
✅ Loaded rows 2,900,000–2,925,000 (2,925,000/3,767,444) | Chunk 117/151
✅ Loaded rows 2,925,000–2,950,000 (2,950,000/3,767,444) | Chunk 118/151
✅ Loaded rows 2,950,000–2,975,000 (2,975,000/3,767,444) | Chunk 119/151
✅ Loaded rows 2,975,000–3,000,000 (3,000,000/3,767,444) | Chunk 120/151
✅ Loaded rows 3,000,000–3,025,000 (3,025,000/3,767,444) | Chunk 121/151
✅ Loaded rows 3,025,000–3,050,000 (3,050,000/3,767,444) | Chunk 122/151
✅ Loaded rows 3,050,000–3,075,000 (3,075,000/3,767,444) | Chunk 123/151
✅ Loaded rows 3,075,000–3,100,000 (3,100,000/3,767,444) | Chunk 124/151
✅ Loaded rows 3,100,000–3,125,000 (3,125,000/3,767,444) | Chunk 125/151
✅ Loaded rows 3,125,000–3,150,000 (3,150,000/3,767,444) | Chunk 126/151
✅ Loaded rows 3,150,000–3,175,000 (3,175,000/3,767,444) | Chunk 127/151
✅ Loaded rows 3,175,000–3,200,000 (3,200,000/3,767,444) | Chunk 128/151
✅ Loaded rows 3,200,000–3,225,000 (3,225,000/3,767,444) | Chunk 129/151
✅ Loaded rows 3,225,000–3,250,000 (3,250,000/3,767,444) | Chunk 130/151
✅ Loaded rows 3,250,000–3,275,000 (3,275,000/3,767,444) | Chunk 131/151
✅ Loaded rows 3,275,000–3,300,000 (3,300,000/3,767,444) | Chunk 132/151
✅ Loaded rows 3,300,000–3,325,000 (3,325,000/3,767,444) | Chunk 133/151
✅ Loaded rows 3,325,000–3,350,000 (3,350,000/3,767,444) | Chunk 134/151
✅ Loaded rows 3,350,000–3,375,000 (3,375,000/3,767,444) | Chunk 135/151
✅ Loaded rows 3,375,000–3,400,000 (3,400,000/3,767,444) | Chunk 136/151
✅ Loaded rows 3,400,000–3,425,000 (3,425,000/3,767,444) | Chunk 137/151
✅ Loaded rows 3,425,000–3,450,000 (3,450,000/3,767,444) | Chunk 138/151
✅ Loaded rows 3,450,000–3,475,000 (3,475,000/3,767,444) | Chunk 139/151
✅ Loaded rows 3,475,000–3,500,000 (3,500,000/3,767,444) | Chunk 140/151
✅ Loaded rows 3,500,000–3,525,000 (3,525,000/3,767,444) | Chunk 141/151
✅ Loaded rows 3,525,000–3,550,000 (3,550,000/3,767,444) | Chunk 142/151
✅ Loaded rows 3,550,000–3,575,000 (3,575,000/3,767,444) | Chunk 143/151
✅ Loaded rows 3,575,000–3,600,000 (3,600,000/3,767,444) | Chunk 144/151
✅ Loaded rows 3,600,000–3,625,000 (3,625,000/3,767,444) | Chunk 145/151
✅ Loaded rows 3,625,000–3,650,000 (3,650,000/3,767,444) | Chunk 146/151
✅ Loaded rows 3,650,000–3,675,000 (3,675,000/3,767,444) | Chunk 147/151
✅ Loaded rows 3,675,000–3,700,000 (3,700,000/3,767,444) | Chunk 148/151
✅ Loaded rows 3,700,000–3,725,000 (3,725,000/3,767,444) | Chunk 149/151
✅ Loaded rows 3,725,000–3,750,000 (3,750,000/3,767,444) | Chunk 150/151
✅ Loaded rows 3,750,000–3,767,444 (3,767,444/3,767,444) | Chunk 151/151

- dim_port table

In [14]:
load_with_progress(
    df=dimPortCSV,
    table_name="dim_port",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "port_id": BigInteger(),
        "port_name": String(255),
    }
)

✅ Loaded rows 0–1,665 (1,665/1,665) | Chunk 1/1

- dim_shipper table

In [15]:
load_with_progress(
    df=dimShipperCSV,
    table_name="dim_shipper",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "shipper_id": BigInteger(),
        "shipper_party_name": String(255),
        "consignee_address_1": String(255),
        "consignee_address_2": String(255),
        "Consignee_address_3": String(255)
    }
)

✅ Loaded rows 0–25,000 (25,000/3,371,079) | Chunk 1/135
✅ Loaded rows 25,000–50,000 (50,000/3,371,079) | Chunk 2/135
✅ Loaded rows 50,000–75,000 (75,000/3,371,079) | Chunk 3/135
✅ Loaded rows 75,000–100,000 (100,000/3,371,079) | Chunk 4/135
✅ Loaded rows 100,000–125,000 (125,000/3,371,079) | Chunk 5/135
✅ Loaded rows 125,000–150,000 (150,000/3,371,079) | Chunk 6/135
✅ Loaded rows 150,000–175,000 (175,000/3,371,079) | Chunk 7/135
✅ Loaded rows 175,000–200,000 (200,000/3,371,079) | Chunk 8/135
✅ Loaded rows 200,000–225,000 (225,000/3,371,079) | Chunk 9/135
✅ Loaded rows 225,000–250,000 (250,000/3,371,079) | Chunk 10/135
✅ Loaded rows 250,000–275,000 (275,000/3,371,079) | Chunk 11/135
✅ Loaded rows 275,000–300,000 (300,000/3,371,079) | Chunk 12/135
✅ Loaded rows 300,000–325,000 (325,000/3,371,079) | Chunk 13/135
✅ Loaded rows 325,000–350,000 (350,000/3,371,079) | Chunk 14/135
✅ Loaded rows 350,000–375,000 (375,000/3,371,079) | Chunk 15/135
✅ Loaded rows 375,000–400,000 (400,000/3,371,079) | Chunk 16/135
✅ Loaded rows 400,000–425,000 (425,000/3,371,079) | Chunk 17/135
✅ Loaded rows 425,000–450,000 (450,000/3,371,079) | Chunk 18/135
✅ Loaded rows 450,000–475,000 (475,000/3,371,079) | Chunk 19/135
✅ Loaded rows 475,000–500,000 (500,000/3,371,079) | Chunk 20/135
✅ Loaded rows 500,000–525,000 (525,000/3,371,079) | Chunk 21/135
✅ Loaded rows 525,000–550,000 (550,000/3,371,079) | Chunk 22/135
✅ Loaded rows 550,000–575,000 (575,000/3,371,079) | Chunk 23/135
✅ Loaded rows 575,000–600,000 (600,000/3,371,079) | Chunk 24/135
✅ Loaded rows 600,000–625,000 (625,000/3,371,079) | Chunk 25/135
✅ Loaded rows 625,000–650,000 (650,000/3,371,079) | Chunk 26/135
✅ Loaded rows 650,000–675,000 (675,000/3,371,079) | Chunk 27/135
✅ Loaded rows 675,000–700,000 (700,000/3,371,079) | Chunk 28/135
✅ Loaded rows 700,000–725,000 (725,000/3,371,079) | Chunk 29/135
✅ Loaded rows 725,000–750,000 (750,000/3,371,079) | Chunk 30/135
✅ Loaded rows 750,000–775,000 (775,000/3,371,079) | Chunk 31/135
✅ Loaded rows 775,000–800,000 (800,000/3,371,079) | Chunk 32/135
✅ Loaded rows 800,000–825,000 (825,000/3,371,079) | Chunk 33/135
✅ Loaded rows 825,000–850,000 (850,000/3,371,079) | Chunk 34/135
✅ Loaded rows 850,000–875,000 (875,000/3,371,079) | Chunk 35/135
✅ Loaded rows 875,000–900,000 (900,000/3,371,079) | Chunk 36/135
✅ Loaded rows 900,000–925,000 (925,000/3,371,079) | Chunk 37/135
✅ Loaded rows 925,000–950,000 (950,000/3,371,079) | Chunk 38/135
✅ Loaded rows 950,000–975,000 (975,000/3,371,079) | Chunk 39/135
✅ Loaded rows 975,000–1,000,000 (1,000,000/3,371,079) | Chunk 40/135
✅ Loaded rows 1,000,000–1,025,000 (1,025,000/3,371,079) | Chunk 41/135
✅ Loaded rows 1,025,000–1,050,000 (1,050,000/3,371,079) | Chunk 42/135
✅ Loaded rows 1,050,000–1,075,000 (1,075,000/3,371,079) | Chunk 43/135
✅ Loaded rows 1,075,000–1,100,000 (1,100,000/3,371,079) | Chunk 44/135
✅ Loaded rows 1,100,000–1,125,000 (1,125,000/3,371,079) | Chunk 45/135
✅ Loaded rows 1,125,000–1,150,000 (1,150,000/3,371,079) | Chunk 46/135
✅ Loaded rows 1,150,000–1,175,000 (1,175,000/3,371,079) | Chunk 47/135
✅ Loaded rows 1,175,000–1,200,000 (1,200,000/3,371,079) | Chunk 48/135
✅ Loaded rows 1,200,000–1,225,000 (1,225,000/3,371,079) | Chunk 49/135
✅ Loaded rows 1,225,000–1,250,000 (1,250,000/3,371,079) | Chunk 50/135
✅ Loaded rows 1,250,000–1,275,000 (1,275,000/3,371,079) | Chunk 51/135
✅ Loaded rows 1,275,000–1,300,000 (1,300,000/3,371,079) | Chunk 52/135
✅ Loaded rows 1,300,000–1,325,000 (1,325,000/3,371,079) | Chunk 53/135
✅ Loaded rows 1,325,000–1,350,000 (1,350,000/3,371,079) | Chunk 54/135
✅ Loaded rows 1,350,000–1,375,000 (1,375,000/3,371,079) | Chunk 55/135
✅ Loaded rows 1,375,000–1,400,000 (1,400,000/3,371,079) | Chunk 56/135
✅ Loaded rows 1,400,000–1,425,000 (1,425,000/3,371,079) | Chunk 57/135
✅ Loaded rows 1,425,000–1,450,000 (1,450,000/3,371,079) | Chunk 58/135
✅ Loaded rows 1,450,000–1,475,000 (1,475,000/3,371,079) | Chunk 59/135
✅ Loaded rows 1,475,000–1,500,000 (1,500,000/3,371,079) | Chunk 60/135
✅ Loaded rows 1,500,000–1,525,000 (1,525,000/3,371,079) | Chunk 61/135
✅ Loaded rows 1,525,000–1,550,000 (1,550,000/3,371,079) | Chunk 62/135
✅ Loaded rows 1,550,000–1,575,000 (1,575,000/3,371,079) | Chunk 63/135
✅ Loaded rows 1,575,000–1,600,000 (1,600,000/3,371,079) | Chunk 64/135
✅ Loaded rows 1,600,000–1,625,000 (1,625,000/3,371,079) | Chunk 65/135
✅ Loaded rows 1,625,000–1,650,000 (1,650,000/3,371,079) | Chunk 66/135
✅ Loaded rows 1,650,000–1,675,000 (1,675,000/3,371,079) | Chunk 67/135
✅ Loaded rows 1,675,000–1,700,000 (1,700,000/3,371,079) | Chunk 68/135
✅ Loaded rows 1,700,000–1,725,000 (1,725,000/3,371,079) | Chunk 69/135
✅ Loaded rows 1,725,000–1,750,000 (1,750,000/3,371,079) | Chunk 70/135
✅ Loaded rows 1,750,000–1,775,000 (1,775,000/3,371,079) | Chunk 71/135
✅ Loaded rows 1,775,000–1,800,000 (1,800,000/3,371,079) | Chunk 72/135
✅ Loaded rows 1,800,000–1,825,000 (1,825,000/3,371,079) | Chunk 73/135
✅ Loaded rows 1,825,000–1,850,000 (1,850,000/3,371,079) | Chunk 74/135
✅ Loaded rows 1,850,000–1,875,000 (1,875,000/3,371,079) | Chunk 75/135
✅ Loaded rows 1,875,000–1,900,000 (1,900,000/3,371,079) | Chunk 76/135
✅ Loaded rows 1,900,000–1,925,000 (1,925,000/3,371,079) | Chunk 77/135
✅ Loaded rows 1,925,000–1,950,000 (1,950,000/3,371,079) | Chunk 78/135
✅ Loaded rows 1,950,000–1,975,000 (1,975,000/3,371,079) | Chunk 79/135
✅ Loaded rows 1,975,000–2,000,000 (2,000,000/3,371,079) | Chunk 80/135
✅ Loaded rows 2,000,000–2,025,000 (2,025,000/3,371,079) | Chunk 81/135
✅ Loaded rows 2,025,000–2,050,000 (2,050,000/3,371,079) | Chunk 82/135
✅ Loaded rows 2,050,000–2,075,000 (2,075,000/3,371,079) | Chunk 83/135
✅ Loaded rows 2,075,000–2,100,000 (2,100,000/3,371,079) | Chunk 84/135
✅ Loaded rows 2,100,000–2,125,000 (2,125,000/3,371,079) | Chunk 85/135
✅ Loaded rows 2,125,000–2,150,000 (2,150,000/3,371,079) | Chunk 86/135
✅ Loaded rows 2,150,000–2,175,000 (2,175,000/3,371,079) | Chunk 87/135
✅ Loaded rows 2,175,000–2,200,000 (2,200,000/3,371,079) | Chunk 88/135
✅ Loaded rows 2,200,000–2,225,000 (2,225,000/3,371,079) | Chunk 89/135
✅ Loaded rows 2,225,000–2,250,000 (2,250,000/3,371,079) | Chunk 90/135
✅ Loaded rows 2,250,000–2,275,000 (2,275,000/3,371,079) | Chunk 91/135
✅ Loaded rows 2,275,000–2,300,000 (2,300,000/3,371,079) | Chunk 92/135
✅ Loaded rows 2,300,000–2,325,000 (2,325,000/3,371,079) | Chunk 93/135
✅ Loaded rows 2,325,000–2,350,000 (2,350,000/3,371,079) | Chunk 94/135
✅ Loaded rows 2,350,000–2,375,000 (2,375,000/3,371,079) | Chunk 95/135
✅ Loaded rows 2,375,000–2,400,000 (2,400,000/3,371,079) | Chunk 96/135
✅ Loaded rows 2,400,000–2,425,000 (2,425,000/3,371,079) | Chunk 97/135
✅ Loaded rows 2,425,000–2,450,000 (2,450,000/3,371,079) | Chunk 98/135
✅ Loaded rows 2,450,000–2,475,000 (2,475,000/3,371,079) | Chunk 99/135
✅ Loaded rows 2,475,000–2,500,000 (2,500,000/3,371,079) | Chunk 100/135
✅ Loaded rows 2,500,000–2,525,000 (2,525,000/3,371,079) | Chunk 101/135
✅ Loaded rows 2,525,000–2,550,000 (2,550,000/3,371,079) | Chunk 102/135
✅ Loaded rows 2,550,000–2,575,000 (2,575,000/3,371,079) | Chunk 103/135
✅ Loaded rows 2,575,000–2,600,000 (2,600,000/3,371,079) | Chunk 104/135
✅ Loaded rows 2,600,000–2,625,000 (2,625,000/3,371,079) | Chunk 105/135
✅ Loaded rows 2,625,000–2,650,000 (2,650,000/3,371,079) | Chunk 106/135
✅ Loaded rows 2,650,000–2,675,000 (2,675,000/3,371,079) | Chunk 107/135
✅ Loaded rows 2,675,000–2,700,000 (2,700,000/3,371,079) | Chunk 108/135
✅ Loaded rows 2,700,000–2,725,000 (2,725,000/3,371,079) | Chunk 109/135
✅ Loaded rows 2,725,000–2,750,000 (2,750,000/3,371,079) | Chunk 110/135
✅ Loaded rows 2,750,000–2,775,000 (2,775,000/3,371,079) | Chunk 111/135
✅ Loaded rows 2,775,000–2,800,000 (2,800,000/3,371,079) | Chunk 112/135
✅ Loaded rows 2,800,000–2,825,000 (2,825,000/3,371,079) | Chunk 113/135
✅ Loaded rows 2,825,000–2,850,000 (2,850,000/3,371,079) | Chunk 114/135
✅ Loaded rows 2,850,000–2,875,000 (2,875,000/3,371,079) | Chunk 115/135
✅ Loaded rows 2,875,000–2,900,000 (2,900,000/3,371,079) | Chunk 116/135
✅ Loaded rows 2,900,000–2,925,000 (2,925,000/3,371,079) | Chunk 117/135
✅ Loaded rows 2,925,000–2,950,000 (2,950,000/3,371,079) | Chunk 118/135
✅ Loaded rows 2,950,000–2,975,000 (2,975,000/3,371,079) | Chunk 119/135
✅ Loaded rows 2,975,000–3,000,000 (3,000,000/3,371,079) | Chunk 120/135
✅ Loaded rows 3,000,000–3,025,000 (3,025,000/3,371,079) | Chunk 121/135
✅ Loaded rows 3,025,000–3,050,000 (3,050,000/3,371,079) | Chunk 122/135
✅ Loaded rows 3,050,000–3,075,000 (3,075,000/3,371,079) | Chunk 123/135
✅ Loaded rows 3,075,000–3,100,000 (3,100,000/3,371,079) | Chunk 124/135
✅ Loaded rows 3,100,000–3,125,000 (3,125,000/3,371,079) | Chunk 125/135
✅ Loaded rows 3,125,000–3,150,000 (3,150,000/3,371,079) | Chunk 126/135
✅ Loaded rows 3,150,000–3,175,000 (3,175,000/3,371,079) | Chunk 127/135
✅ Loaded rows 3,175,000–3,200,000 (3,200,000/3,371,079) | Chunk 128/135
✅ Loaded rows 3,200,000–3,225,000 (3,225,000/3,371,079) | Chunk 129/135
✅ Loaded rows 3,225,000–3,250,000 (3,250,000/3,371,079) | Chunk 130/135
✅ Loaded rows 3,250,000–3,275,000 (3,275,000/3,371,079) | Chunk 131/135
✅ Loaded rows 3,275,000–3,300,000 (3,300,000/3,371,079) | Chunk 132/135
✅ Loaded rows 3,300,000–3,325,000 (3,325,000/3,371,079) | Chunk 133/135
✅ Loaded rows 3,325,000–3,350,000 (3,350,000/3,371,079) | Chunk 134/135
✅ Loaded rows 3,350,000–3,371,079 (3,371,079/3,371,079) | Chunk 135/135

- dim_vessel table

In [16]:
load_with_progress(
    df=dimVesselCSV,
    table_name="dim_vessel",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "vessel_id": BigInteger(),
        "vessel_country_code": String(30),
        "consignee_name": String(255),
    }
)

✅ Loaded rows 0–25,000 (25,000/38,098) | Chunk 1/2
✅ Loaded rows 25,000–38,098 (38,098/38,098) | Chunk 2/2

- fact_header table

In [17]:
load_with_progress(
    df=factHeaderCSV,
    table_name="fact_header",
    engine=engine,
    schema="dbo",
    chunksize=25_000,
    dtype={
        "identifier": BigInteger(),
        "estimated_arrival_date": Date(),
        "actual_arrival_date": Date(),
        "port_of_unlading_id": BigInteger(),
        "foreign_port_of_lading_qualifier_id": BigInteger(),
        "foreign_port_of_lading_id": BigInteger(),
        "port_of_destination_id": BigInteger(),
        "foreign_port_of_destination_qualifier_id": BigInteger(),
        "foreign_port_of_destination_id": BigInteger(),
        "vessel_id": BigInteger(),
        "shipper_id": BigInteger(),
        "consignee_id": BigInteger(),
        "manifest_quantity": BigInteger(),
        "weight": BigInteger(),
        "measurement": BigInteger()
    }
)

✅ Loaded rows 0–25,000 (25,000/34,038,979) | Chunk 1/1362
✅ Loaded rows 25,000–50,000 (50,000/34,038,979) | Chunk 2/1362
✅ Loaded rows 50,000–75,000 (75,000/34,038,979) | Chunk 3/1362
✅ Loaded rows 75,000–100,000 (100,000/34,038,979) | Chunk 4/1362
✅ Loaded rows 100,000–125,000 (125,000/34,038,979) | Chunk 5/1362
✅ Loaded rows 125,000–150,000 (150,000/34,038,979) | Chunk 6/1362
✅ Loaded rows 150,000–175,000 (175,000/34,038,979) | Chunk 7/1362
✅ Loaded rows 175,000–200,000 (200,000/34,038,979) | Chunk 8/1362
✅ Loaded rows 200,000–225,000 (225,000/34,038,979) | Chunk 9/1362
✅ Loaded rows 225,000–250,000 (250,000/34,038,979) | Chunk 10/1362
✅ Loaded rows 250,000–275,000 (275,000/34,038,979) | Chunk 11/1362
✅ Loaded rows 275,000–300,000 (300,000/34,038,979) | Chunk 12/1362
✅ Loaded rows 300,000–325,000 (325,000/34,038,979) | Chunk 13/1362
✅ Loaded rows 325,000–350,000 (350,000/34,038,979) | Chunk 14/1362
✅ Loaded rows 350,000–375,000 (375,000/34,038,979) | Chunk 15/1362
✅ Loaded rows 375,000–400,000 (400,000/34,038,979) | Chunk 16/1362
✅ Loaded rows 400,000–425,000 (425,000/34,038,979) | Chunk 17/1362
✅ Loaded rows 425,000–450,000 (450,000/34,038,979) | Chunk 18/1362
✅ Loaded rows 450,000–475,000 (475,000/34,038,979) | Chunk 19/1362
✅ Loaded rows 475,000–500,000 (500,000/34,038,979) | Chunk 20/1362
✅ Loaded rows 500,000–525,000 (525,000/34,038,979) | Chunk 21/1362
✅ Loaded rows 525,000–550,000 (550,000/34,038,979) | Chunk 22/1362
✅ Loaded rows 550,000–575,000 (575,000/34,038,979) | Chunk 23/1362
✅ Loaded rows 575,000–600,000 (600,000/34,038,979) | Chunk 24/1362
✅ Loaded rows 600,000–625,000 (625,000/34,038,979) | Chunk 25/1362
✅ Loaded rows 625,000–650,000 (650,000/34,038,979) | Chunk 26/1362
✅ Loaded rows 650,000–675,000 (675,000/34,038,979) | Chunk 27/1362
✅ Loaded rows 675,000–700,000 (700,000/34,038,979) | Chunk 28/1362
✅ Loaded rows 700,000–725,000 (725,000/34,038,979) | Chunk 29/1362
✅ Loaded rows 725,000–750,000 (750,000/34,038,979) | Chunk 30/1362
✅ Loaded rows 750,000–775,000 (775,000/34,038,979) | Chunk 31/1362
✅ Loaded rows 775,000–800,000 (800,000/34,038,979) | Chunk 32/1362
✅ Loaded rows 800,000–825,000 (825,000/34,038,979) | Chunk 33/1362
✅ Loaded rows 825,000–850,000 (850,000/34,038,979) | Chunk 34/1362
✅ Loaded rows 850,000–875,000 (875,000/34,038,979) | Chunk 35/1362
✅ Loaded rows 875,000–900,000 (900,000/34,038,979) | Chunk 36/1362
✅ Loaded rows 900,000–925,000 (925,000/34,038,979) | Chunk 37/1362
✅ Loaded rows 925,000–950,000 (950,000/34,038,979) | Chunk 38/1362
✅ Loaded rows 950,000–975,000 (975,000/34,038,979) | Chunk 39/1362
✅ Loaded rows 975,000–1,000,000 (1,000,000/34,038,979) | Chunk 40/1362
✅ Loaded rows 1,000,000–1,025,000 (1,025,000/34,038,979) | Chunk 41/1362
✅ Loaded rows 1,025,000–1,050,000 (1,050,000/34,038,979) | Chunk 42/1362
✅ Loaded rows 1,050,000–1,075,000 (1,075,000/34,038,979) | Chunk 43/1362
✅ Loaded rows 1,075,000–1,100,000 (1,100,000/34,038,979) | Chunk 44/1362
✅ Loaded rows 1,100,000–1,125,000 (1,125,000/34,038,979) | Chunk 45/1362
✅ Loaded rows 1,125,000–1,150,000 (1,150,000/34,038,979) | Chunk 46/1362
✅ Loaded rows 1,150,000–1,175,000 (1,175,000/34,038,979) | Chunk 47/1362
✅ Loaded rows 1,175,000–1,200,000 (1,200,000/34,038,979) | Chunk 48/1362
✅ Loaded rows 1,200,000–1,225,000 (1,225,000/34,038,979) | Chunk 49/1362
✅ Loaded rows 1,225,000–1,250,000 (1,250,000/34,038,979) | Chunk 50/1362
✅ Loaded rows 1,250,000–1,275,000 (1,275,000/34,038,979) | Chunk 51/1362
✅ Loaded rows 1,275,000–1,300,000 (1,300,000/34,038,979) | Chunk 52/1362
✅ Loaded rows 1,300,000–1,325,000 (1,325,000/34,038,979) | Chunk 53/1362
✅ Loaded rows 1,325,000–1,350,000 (1,350,000/34,038,979) | Chunk 54/1362
✅ Loaded rows 1,350,000–1,375,000 (1,375,000/34,038,979) | Chunk 55/1362
✅ Loaded rows 1,375,000–1,400,000 (1,400,000/34,038,979) | Chunk 56/1362
✅ Loaded rows 1,400,000–1,425,000 (1,425,000/34,038,979) | Chunk 57/1362
✅ Loaded rows 1,425,000–1,450,000 (1,450,000/34,038,979) | Chunk 58/1362
✅ Loaded rows 1,450,000–1,475,000 (1,475,000/34,038,979) | Chunk 59/1362
✅ Loaded rows 1,475,000–1,500,000 (1,500,000/34,038,979) | Chunk 60/1362
✅ Loaded rows 1,500,000–1,525,000 (1,525,000/34,038,979) | Chunk 61/1362
✅ Loaded rows 1,525,000–1,550,000 (1,550,000/34,038,979) | Chunk 62/1362
✅ Loaded rows 1,550,000–1,575,000 (1,575,000/34,038,979) | Chunk 63/1362
✅ Loaded rows 1,575,000–1,600,000 (1,600,000/34,038,979) | Chunk 64/1362
✅ Loaded rows 1,600,000–1,625,000 (1,625,000/34,038,979) | Chunk 65/1362
✅ Loaded rows 1,625,000–1,650,000 (1,650,000/34,038,979) | Chunk 66/1362
✅ Loaded rows 1,650,000–1,675,000 (1,675,000/34,038,979) | Chunk 67/1362
✅ Loaded rows 1,675,000–1,700,000 (1,700,000/34,038,979) | Chunk 68/1362
✅ Loaded rows 1,700,000–1,725,000 (1,725,000/34,038,979) | Chunk 69/1362
✅ Loaded rows 1,725,000–1,750,000 (1,750,000/34,038,979) | Chunk 70/1362
✅ Loaded rows 1,750,000–1,775,000 (1,775,000/34,038,979) | Chunk 71/1362
✅ Loaded rows 1,775,000–1,800,000 (1,800,000/34,038,979) | Chunk 72/1362
✅ Loaded rows 1,800,000–1,825,000 (1,825,000/34,038,979) | Chunk 73/1362
✅ Loaded rows 1,825,000–1,850,000 (1,850,000/34,038,979) | Chunk 74/1362
✅ Loaded rows 1,850,000–1,875,000 (1,875,000/34,038,979) | Chunk 75/1362
✅ Loaded rows 1,875,000–1,900,000 (1,900,000/34,038,979) | Chunk 76/1362
✅ Loaded rows 1,900,000–1,925,000 (1,925,000/34,038,979) | Chunk 77/1362
✅ Loaded rows 1,925,000–1,950,000 (1,950,000/34,038,979) | Chunk 78/1362
✅ Loaded rows 1,950,000–1,975,000 (1,975,000/34,038,979) | Chunk 79/1362
✅ Loaded rows 1,975,000–2,000,000 (2,000,000/34,038,979) | Chunk 80/1362
✅ Loaded rows 2,000,000–2,025,000 (2,025,000/34,038,979) | Chunk 81/1362
✅ Loaded rows 2,025,000–2,050,000 (2,050,000/34,038,979) | Chunk 82/1362
✅ Loaded rows 2,050,000–2,075,000 (2,075,000/34,038,979) | Chunk 83/1362
✅ Loaded rows 2,075,000–2,100,000 (2,100,000/34,038,979) | Chunk 84/1362
✅ Loaded rows 2,100,000–2,125,000 (2,125,000/34,038,979) | Chunk 85/1362
✅ Loaded rows 2,125,000–2,150,000 (2,150,000/34,038,979) | Chunk 86/1362
✅ Loaded rows 2,150,000–2,175,000 (2,175,000/34,038,979) | Chunk 87/1362
✅ Loaded rows 2,175,000–2,200,000 (2,200,000/34,038,979) | Chunk 88/1362
✅ Loaded rows 2,200,000–2,225,000 (2,225,000/34,038,979) | Chunk 89/1362
✅ Loaded rows 2,225,000–2,250,000 (2,250,000/34,038,979) | Chunk 90/1362
✅ Loaded rows 2,250,000–2,275,000 (2,275,000/34,038,979) | Chunk 91/1362
✅ Loaded rows 2,275,000–2,300,000 (2,300,000/34,038,979) | Chunk 92/1362
✅ Loaded rows 2,300,000–2,325,000 (2,325,000/34,038,979) | Chunk 93/1362
✅ Loaded rows 2,325,000–2,350,000 (2,350,000/34,038,979) | Chunk 94/1362
✅ Loaded rows 2,350,000–2,375,000 (2,375,000/34,038,979) | Chunk 95/1362
✅ Loaded rows 2,375,000–2,400,000 (2,400,000/34,038,979) | Chunk 96/1362
✅ Loaded rows 2,400,000–2,425,000 (2,425,000/34,038,979) | Chunk 97/1362
✅ Loaded rows 2,425,000–2,450,000 (2,450,000/34,038,979) | Chunk 98/1362
✅ Loaded rows 2,450,000–2,475,000 (2,475,000/34,038,979) | Chunk 99/1362
✅ Loaded rows 2,475,000–2,500,000 (2,500,000/34,038,979) | Chunk 100/1362
✅ Loaded rows 2,500,000–2,525,000 (2,525,000/34,038,979) | Chunk 101/1362
✅ Loaded rows 2,525,000–2,550,000 (2,550,000/34,038,979) | Chunk 102/1362
✅ Loaded rows 2,550,000–2,575,000 (2,575,000/34,038,979) | Chunk 103/1362
✅ Loaded rows 2,575,000–2,600,000 (2,600,000/34,038,979) | Chunk 104/1362
✅ Loaded rows 2,600,000–2,625,000 (2,625,000/34,038,979) | Chunk 105/1362
✅ Loaded rows 2,625,000–2,650,000 (2,650,000/34,038,979) | Chunk 106/1362
✅ Loaded rows 2,650,000–2,675,000 (2,675,000/34,038,979) | Chunk 107/1362
✅ Loaded rows 2,675,000–2,700,000 (2,700,000/34,038,979) | Chunk 108/1362
✅ Loaded rows 2,700,000–2,725,000 (2,725,000/34,038,979) | Chunk 109/1362
✅ Loaded rows 2,725,000–2,750,000 (2,750,000/34,038,979) | Chunk 110/1362
✅ Loaded rows 2,750,000–2,775,000 (2,775,000/34,038,979) | Chunk 111/1362
✅ Loaded rows 2,775,000–2,800,000 (2,800,000/34,038,979) | Chunk 112/1362
✅ Loaded rows 2,800,000–2,825,000 (2,825,000/34,038,979) | Chunk 113/1362
✅ Loaded rows 2,825,000–2,850,000 (2,850,000/34,038,979) | Chunk 114/1362
✅ Loaded rows 2,850,000–2,875,000 (2,875,000/34,038,979) | Chunk 115/1362
✅ Loaded rows 2,875,000–2,900,000 (2,900,000/34,038,979) | Chunk 116/1362
✅ Loaded rows 2,900,000–2,925,000 (2,925,000/34,038,979) | Chunk 117/1362
✅ Loaded rows 2,925,000–2,950,000 (2,950,000/34,038,979) | Chunk 118/1362
✅ Loaded rows 2,950,000–2,975,000 (2,975,000/34,038,979) | Chunk 119/1362
✅ Loaded rows 2,975,000–3,000,000 (3,000,000/34,038,979) | Chunk 120/1362
✅ Loaded rows 3,000,000–3,025,000 (3,025,000/34,038,979) | Chunk 121/1362
✅ Loaded rows 3,025,000–3,050,000 (3,050,000/34,038,979) | Chunk 122/1362
✅ Loaded rows 3,050,000–3,075,000 (3,075,000/34,038,979) | Chunk 123/1362
✅ Loaded rows 3,075,000–3,100,000 (3,100,000/34,038,979) | Chunk 124/1362
✅ Loaded rows 3,100,000–3,125,000 (3,125,000/34,038,979) | Chunk 125/1362
✅ Loaded rows 3,125,000–3,150,000 (3,150,000/34,038,979) | Chunk 126/1362
✅ Loaded rows 3,150,000–3,175,000 (3,175,000/34,038,979) | Chunk 127/1362
✅ Loaded rows 3,175,000–3,200,000 (3,200,000/34,038,979) | Chunk 128/1362
✅ Loaded rows 3,200,000–3,225,000 (3,225,000/34,038,979) | Chunk 129/1362
✅ Loaded rows 3,225,000–3,250,000 (3,250,000/34,038,979) | Chunk 130/1362
✅ Loaded rows 3,250,000–3,275,000 (3,275,000/34,038,979) | Chunk 131/1362
✅ Loaded rows 3,275,000–3,300,000 (3,300,000/34,038,979) | Chunk 132/1362
✅ Loaded rows 3,300,000–3,325,000 (3,325,000/34,038,979) | Chunk 133/1362
✅ Loaded rows 3,325,000–3,350,000 (3,350,000/34,038,979) | Chunk 134/1362
✅ Loaded rows 3,350,000–3,375,000 (3,375,000/34,038,979) | Chunk 135/1362
✅ Loaded rows 3,375,000–3,400,000 (3,400,000/34,038,979) | Chunk 136/1362
✅ Loaded rows 3,400,000–3,425,000 (3,425,000/34,038,979) | Chunk 137/1362
✅ Loaded rows 3,425,000–3,450,000 (3,450,000/34,038,979) | Chunk 138/1362
✅ Loaded rows 3,450,000–3,475,000 (3,475,000/34,038,979) | Chunk 139/1362
✅ Loaded rows 3,475,000–3,500,000 (3,500,000/34,038,979) | Chunk 140/1362
✅ Loaded rows 3,500,000–3,525,000 (3,525,000/34,038,979) | Chunk 141/1362
✅ Loaded rows 3,525,000–3,550,000 (3,550,000/34,038,979) | Chunk 142/1362
✅ Loaded rows 3,550,000–3,575,000 (3,575,000/34,038,979) | Chunk 143/1362
✅ Loaded rows 3,575,000–3,600,000 (3,600,000/34,038,979) | Chunk 144/1362
✅ Loaded rows 3,600,000–3,625,000 (3,625,000/34,038,979) | Chunk 145/1362
✅ Loaded rows 3,625,000–3,650,000 (3,650,000/34,038,979) | Chunk 146/1362
✅ Loaded rows 3,650,000–3,675,000 (3,675,000/34,038,979) | Chunk 147/1362
✅ Loaded rows 3,675,000–3,700,000 (3,700,000/34,038,979) | Chunk 148/1362
✅ Loaded rows 3,700,000–3,725,000 (3,725,000/34,038,979) | Chunk 149/1362
✅ Loaded rows 3,725,000–3,750,000 (3,750,000/34,038,979) | Chunk 150/1362
✅ Loaded rows 3,750,000–3,775,000 (3,775,000/34,038,979) | Chunk 151/1362
✅ Loaded rows 3,775,000–3,800,000 (3,800,000/34,038,979) | Chunk 152/1362
✅ Loaded rows 3,800,000–3,825,000 (3,825,000/34,038,979) | Chunk 153/1362
✅ Loaded rows 3,825,000–3,850,000 (3,850,000/34,038,979) | Chunk 154/1362
✅ Loaded rows 3,850,000–3,875,000 (3,875,000/34,038,979) | Chunk 155/1362
✅ Loaded rows 3,875,000–3,900,000 (3,900,000/34,038,979) | Chunk 156/1362
✅ Loaded rows 3,900,000–3,925,000 (3,925,000/34,038,979) | Chunk 157/1362
✅ Loaded rows 3,925,000–3,950,000 (3,950,000/34,038,979) | Chunk 158/1362
✅ Loaded rows 3,950,000–3,975,000 (3,975,000/34,038,979) | Chunk 159/1362
✅ Loaded rows 3,975,000–4,000,000 (4,000,000/34,038,979) | Chunk 160/1362
✅ Loaded rows 4,000,000–4,025,000 (4,025,000/34,038,979) | Chunk 161/1362
✅ Loaded rows 4,025,000–4,050,000 (4,050,000/34,038,979) | Chunk 162/1362
✅ Loaded rows 4,050,000–4,075,000 (4,075,000/34,038,979) | Chunk 163/1362
✅ Loaded rows 4,075,000–4,100,000 (4,100,000/34,038,979) | Chunk 164/1362
✅ Loaded rows 4,100,000–4,125,000 (4,125,000/34,038,979) | Chunk 165/1362
✅ Loaded rows 4,125,000–4,150,000 (4,150,000/34,038,979) | Chunk 166/1362
✅ Loaded rows 4,150,000–4,175,000 (4,175,000/34,038,979) | Chunk 167/1362
✅ Loaded rows 4,175,000–4,200,000 (4,200,000/34,038,979) | Chunk 168/1362
✅ Loaded rows 4,200,000–4,225,000 (4,225,000/34,038,979) | Chunk 169/1362
✅ Loaded rows 4,225,000–4,250,000 (4,250,000/34,038,979) | Chunk 170/1362
✅ Loaded rows 4,250,000–4,275,000 (4,275,000/34,038,979) | Chunk 171/1362
✅ Loaded rows 4,275,000–4,300,000 (4,300,000/34,038,979) | Chunk 172/1362
✅ Loaded rows 4,300,000–4,325,000 (4,325,000/34,038,979) | Chunk 173/1362
✅ Loaded rows 4,325,000–4,350,000 (4,350,000/34,038,979) | Chunk 174/1362
✅ Loaded rows 4,350,000–4,375,000 (4,375,000/34,038,979) | Chunk 175/1362
✅ Loaded rows 4,375,000–4,400,000 (4,400,000/34,038,979) | Chunk 176/1362
✅ Loaded rows 4,400,000–4,425,000 (4,425,000/34,038,979) | Chunk 177/1362
✅ Loaded rows 4,425,000–4,450,000 (4,450,000/34,038,979) | Chunk 178/1362
✅ Loaded rows 4,450,000–4,475,000 (4,475,000/34,038,979) | Chunk 179/1362
✅ Loaded rows 4,475,000–4,500,000 (4,500,000/34,038,979) | Chunk 180/1362
✅ Loaded rows 4,500,000–4,525,000 (4,525,000/34,038,979) | Chunk 181/1362
✅ Loaded rows 4,525,000–4,550,000 (4,550,000/34,038,979) | Chunk 182/1362
✅ Loaded rows 4,550,000–4,575,000 (4,575,000/34,038,979) | Chunk 183/1362
✅ Loaded rows 4,575,000–4,600,000 (4,600,000/34,038,979) | Chunk 184/1362
✅ Loaded rows 4,600,000–4,625,000 (4,625,000/34,038,979) | Chunk 185/1362
✅ Loaded rows 4,625,000–4,650,000 (4,650,000/34,038,979) | Chunk 186/1362
✅ Loaded rows 4,650,000–4,675,000 (4,675,000/34,038,979) | Chunk 187/1362
✅ Loaded rows 4,675,000–4,700,000 (4,700,000/34,038,979) | Chunk 188/1362
✅ Loaded rows 4,700,000–4,725,000 (4,725,000/34,038,979) | Chunk 189/1362
✅ Loaded rows 4,725,000–4,750,000 (4,750,000/34,038,979) | Chunk 190/1362
✅ Loaded rows 4,750,000–4,775,000 (4,775,000/34,038,979) | Chunk 191/1362
✅ Loaded rows 4,775,000–4,800,000 (4,800,000/34,038,979) | Chunk 192/1362
✅ Loaded rows 4,800,000–4,825,000 (4,825,000/34,038,979) | Chunk 193/1362
✅ Loaded rows 4,825,000–4,850,000 (4,850,000/34,038,979) | Chunk 194/1362
✅ Loaded rows 4,850,000–4,875,000 (4,875,000/34,038,979) | Chunk 195/1362
✅ Loaded rows 4,875,000–4,900,000 (4,900,000/34,038,979) | Chunk 196/1362
✅ Loaded rows 4,900,000–4,925,000 (4,925,000/34,038,979) | Chunk 197/1362
✅ Loaded rows 4,925,000–4,950,000 (4,950,000/34,038,979) | Chunk 198/1362
✅ Loaded rows 4,950,000–4,975,000 (4,975,000/34,038,979) | Chunk 199/1362
✅ Loaded rows 4,975,000–5,000,000 (5,000,000/34,038,979) | Chunk 200/1362
✅ Loaded rows 5,000,000–5,025,000 (5,025,000/34,038,979) | Chunk 201/1362
✅ Loaded rows 5,025,000–5,050,000 (5,050,000/34,038,979) | Chunk 202/1362
✅ Loaded rows 5,050,000–5,075,000 (5,075,000/34,038,979) | Chunk 203/1362
✅ Loaded rows 5,075,000–5,100,000 (5,100,000/34,038,979) | Chunk 204/1362
✅ Loaded rows 5,100,000–5,125,000 (5,125,000/34,038,979) | Chunk 205/1362
✅ Loaded rows 5,125,000–5,150,000 (5,150,000/34,038,979) | Chunk 206/1362
✅ Loaded rows 5,150,000–5,175,000 (5,175,000/34,038,979) | Chunk 207/1362
✅ Loaded rows 5,175,000–5,200,000 (5,200,000/34,038,979) | Chunk 208/1362
✅ Loaded rows 5,200,000–5,225,000 (5,225,000/34,038,979) | Chunk 209/1362
✅ Loaded rows 5,225,000–5,250,000 (5,250,000/34,038,979) | Chunk 210/1362
✅ Loaded rows 5,250,000–5,275,000 (5,275,000/34,038,979) | Chunk 211/1362
✅ Loaded rows 5,275,000–5,300,000 (5,300,000/34,038,979) | Chunk 212/1362
✅ Loaded rows 5,300,000–5,325,000 (5,325,000/34,038,979) | Chunk 213/1362
✅ Loaded rows 5,325,000–5,350,000 (5,350,000/34,038,979) | Chunk 214/1362
✅ Loaded rows 5,350,000–5,375,000 (5,375,000/34,038,979) | Chunk 215/1362
✅ Loaded rows 5,375,000–5,400,000 (5,400,000/34,038,979) | Chunk 216/1362
✅ Loaded rows 5,400,000–5,425,000 (5,425,000/34,038,979) | Chunk 217/1362
✅ Loaded rows 5,425,000–5,450,000 (5,450,000/34,038,979) | Chunk 218/1362
✅ Loaded rows 5,450,000–5,475,000 (5,475,000/34,038,979) | Chunk 219/1362
✅ Loaded rows 5,475,000–5,500,000 (5,500,000/34,038,979) | Chunk 220/1362
✅ Loaded rows 5,500,000–5,525,000 (5,525,000/34,038,979) | Chunk 221/1362
✅ Loaded rows 5,525,000–5,550,000 (5,550,000/34,038,979) | Chunk 222/1362
✅ Loaded rows 5,550,000–5,575,000 (5,575,000/34,038,979) | Chunk 223/1362
✅ Loaded rows 5,575,000–5,600,000 (5,600,000/34,038,979) | Chunk 224/1362
✅ Loaded rows 5,600,000–5,625,000 (5,625,000/34,038,979) | Chunk 225/1362
✅ Loaded rows 5,625,000–5,650,000 (5,650,000/34,038,979) | Chunk 226/1362
✅ Loaded rows 5,650,000–5,675,000 (5,675,000/34,038,979) | Chunk 227/1362
✅ Loaded rows 5,675,000–5,700,000 (5,700,000/34,038,979) | Chunk 228/1362
✅ Loaded rows 5,700,000–5,725,000 (5,725,000/34,038,979) | Chunk 229/1362
✅ Loaded rows 5,725,000–5,750,000 (5,750,000/34,038,979) | Chunk 230/1362
✅ Loaded rows 5,750,000–5,775,000 (5,775,000/34,038,979) | Chunk 231/1362
✅ Loaded rows 5,775,000–5,800,000 (5,800,000/34,038,979) | Chunk 232/1362
✅ Loaded rows 5,800,000–5,825,000 (5,825,000/34,038,979) | Chunk 233/1362
✅ Loaded rows 5,825,000–5,850,000 (5,850,000/34,038,979) | Chunk 234/1362
✅ Loaded rows 5,850,000–5,875,000 (5,875,000/34,038,979) | Chunk 235/1362
✅ Loaded rows 5,875,000–5,900,000 (5,900,000/34,038,979) | Chunk 236/1362
✅ Loaded rows 5,900,000–5,925,000 (5,925,000/34,038,979) | Chunk 237/1362
✅ Loaded rows 5,925,000–5,950,000 (5,950,000/34,038,979) | Chunk 238/1362
✅ Loaded rows 5,950,000–5,975,000 (5,975,000/34,038,979) | Chunk 239/1362
✅ Loaded rows 5,975,000–6,000,000 (6,000,000/34,038,979) | Chunk 240/1362
✅ Loaded rows 6,000,000–6,025,000 (6,025,000/34,038,979) | Chunk 241/1362
✅ Loaded rows 6,025,000–6,050,000 (6,050,000/34,038,979) | Chunk 242/1362
✅ Loaded rows 6,050,000–6,075,000 (6,075,000/34,038,979) | Chunk 243/1362
✅ Loaded rows 6,075,000–6,100,000 (6,100,000/34,038,979) | Chunk 244/1362
✅ Loaded rows 6,100,000–6,125,000 (6,125,000/34,038,979) | Chunk 245/1362
✅ Loaded rows 6,125,000–6,150,000 (6,150,000/34,038,979) | Chunk 246/1362
✅ Loaded rows 6,150,000–6,175,000 (6,175,000/34,038,979) | Chunk 247/1362
✅ Loaded rows 6,175,000–6,200,000 (6,200,000/34,038,979) | Chunk 248/1362
✅ Loaded rows 6,200,000–6,225,000 (6,225,000/34,038,979) | Chunk 249/1362
✅ Loaded rows 6,225,000–6,250,000 (6,250,000/34,038,979) | Chunk 250/1362
✅ Loaded rows 6,250,000–6,275,000 (6,275,000/34,038,979) | Chunk 251/1362
✅ Loaded rows 6,275,000–6,300,000 (6,300,000/34,038,979) | Chunk 252/1362
✅ Loaded rows 6,300,000–6,325,000 (6,325,000/34,038,979) | Chunk 253/1362
✅ Loaded rows 6,325,000–6,350,000 (6,350,000/34,038,979) | Chunk 254/1362
✅ Loaded rows 6,350,000–6,375,000 (6,375,000/34,038,979) | Chunk 255/1362
✅ Loaded rows 6,375,000–6,400,000 (6,400,000/34,038,979) | Chunk 256/1362
✅ Loaded rows 6,400,000–6,425,000 (6,425,000/34,038,979) | Chunk 257/1362
✅ Loaded rows 6,425,000–6,450,000 (6,450,000/34,038,979) | Chunk 258/1362
✅ Loaded rows 6,450,000–6,475,000 (6,475,000/34,038,979) | Chunk 259/1362
✅ Loaded rows 6,475,000–6,500,000 (6,500,000/34,038,979) | Chunk 260/1362
✅ Loaded rows 6,500,000–6,525,000 (6,525,000/34,038,979) | Chunk 261/1362
✅ Loaded rows 6,525,000–6,550,000 (6,550,000/34,038,979) | Chunk 262/1362
✅ Loaded rows 6,550,000–6,575,000 (6,575,000/34,038,979) | Chunk 263/1362
✅ Loaded rows 6,575,000–6,600,000 (6,600,000/34,038,979) | Chunk 264/1362
✅ Loaded rows 6,600,000–6,625,000 (6,625,000/34,038,979) | Chunk 265/1362
✅ Loaded rows 6,625,000–6,650,000 (6,650,000/34,038,979) | Chunk 266/1362
✅ Loaded rows 6,650,000–6,675,000 (6,675,000/34,038,979) | Chunk 267/1362
✅ Loaded rows 6,675,000–6,700,000 (6,700,000/34,038,979) | Chunk 268/1362
✅ Loaded rows 6,700,000–6,725,000 (6,725,000/34,038,979) | Chunk 269/1362
✅ Loaded rows 6,725,000–6,750,000 (6,750,000/34,038,979) | Chunk 270/1362
✅ Loaded rows 6,750,000–6,775,000 (6,775,000/34,038,979) | Chunk 271/1362
✅ Loaded rows 6,775,000–6,800,000 (6,800,000/34,038,979) | Chunk 272/1362
✅ Loaded rows 6,800,000–6,825,000 (6,825,000/34,038,979) | Chunk 273/1362
✅ Loaded rows 6,825,000–6,850,000 (6,850,000/34,038,979) | Chunk 274/1362
✅ Loaded rows 6,850,000–6,875,000 (6,875,000/34,038,979) | Chunk 275/1362